---
parser: "@typescript-eslint/parser"

parserOptions:
    sourceType: module

plugins:
    - "@typescript-eslint"
    - prettier
    - mocha
    - react
    - react-hooks
    - import

extends:
    - "eslint:recommended"
    - "plugin:@typescript-eslint/eslint-recommended"

ignorePatterns:
    - "/node_modules/"
    - "/src/generated/"
    - "/build/"

env:
    es6: true
    node: true
    mocha: true

globals:
    window: true
    document: true
    process: true

settings:
    import/resolver:
        alias:
            extensions: [".tsx", ".json"]
    import/external-modules-folders: ["node_modules"]
    react:
        version: detect

rules:
    dot-location: 0
    dot-notation: 2
    eqeqeq: 2
    jsx-quotes: [2, "prefer-double"]
    no-debugger: 2
    no-console: 2
    no-extra-semi: 2
    no-irregular-whitespace: 2

    # We only want ot import e.g. `lodash.map` and never `lodash` or `lodash/map`
    # However, we need to have it as a dependency for compantibility with benchmark.js
    # Therefore, we forbid said imports here
    no-restricted-imports: [2, { "paths": ["lodash"], "patterns": ["lodash.*"] }]

    no-shadow: 2
    no-undef: 2
    no-unused-expressions: 0
    # no-unused-vars: [2, { "ignoreRestSiblings": true }]
    "@typescript-eslint/no-unused-vars": [2, { "ignoreRestSiblings": true }]
    no-var: 2
    radix: 2

    # eslint-plugin-import
    # import/named: 2
    import/default: 2
    import/export: 2

    import/first: 2
    import/newline-after-import: 2
    import/no-absolute-path: 2
    import/no-duplicates: 2
    import/no-dynamic-require: 2
    import/no-extraneous-dependencies: 2
    import/no-mutable-exports: 2

    import/order: [2, { "newlines-between": "always", "groups": ["builtin", "external", "internal", "parent", "sibling", "index"] }]
    # We don't always want to import all exports of a modules index.js
    # Therefore, we forbid said imports here

    # eslint-plugin-react
    react/react-in-jsx-scope: 2
    react/jsx-boolean-value: [2, always]
    react/jsx-no-bind: [2, { allowArrowFunctions: true }]
    react/jsx-no-undef: 2
    react/jsx-uses-react: 2
    react/jsx-uses-vars: 2
    react/no-multi-comp: [2, { "ignoreStateless": true }]
    react/no-unknown-property: 2
    react/sort-comp: 0

    # eslint-plugin-react-hooks
    react-hooks/rules-of-hooks: "error"
    react-hooks/exhaustive-deps: "error"

    # eslint-plugin-prettier
    prettier/prettier: "error"
